server:
  port: 9090
  servlet:
    context-path: /authority


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.21:3306/auth_system?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xyz.ibudai.authority.model.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


token:
  hosts: "*"
  issuer: ibudai
  secret: auth_2025
  expireMinutes: 30
  whitelist:
    - ${server.servlet.context-path}/api/user/login